canonical/microcloud

- microcloud/service/lxd.go
- microcloud/service/lxd_init.go
This addresses @stgraber's comments from IRC:
* There is now a helper to get the LXD client rather than calling `ConnectLXD` right away.
* Reverts initialization to use the API again. The helper here is basically `initDataNodeApply` from LXD with the project related parts stripped out.
* Uses `zfs` for the storage driver
* Bootstraps LXD with a `lxdfan0` network device
> Init updates

- microcloud/cmd/microcloud/main_init.go
- microcloud/service/service_handler.go
Adds  a `RunAsync` function to the service handler that will run the given hook on all services asynchronously. 
Right now this is used for bootstrapping, issuing tokens, and joining all services.
> Run service actions asynchronously

- microcloud/cmd/microcloud/main_init.go
- microcloud/mdns/lookup.go
On `init`, MicroCloud starts an mdns broadcast with all the join tokens for each service and peer as the text body. What this means is that all peers will attempt to join through that first initial member.
In some cases this can cause issues as a cluster rebalances roles as it grows. So this PR splits the broadcast in two. First we send out a broadcast with just 2 members, and wait for a few seconds before continuing with the rest.
> Sleep between cluster role reshuffling when sending tokens

- snapcraft.yaml
This is needed to allow wiping of disks on MicroCloud servers prior to their addition as a ZFS storage pool into LXD.
> snapcraft: Add block-devices interface

- microcloud/cmd/microcloud/main_init.go
Skip adding local storage if we have insufficient disks for remote storage and we are forming the cluster automatically.
> Only skip adding disks in --auto mode

- microcloud/api/services.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloudd/main.go
- microcloud/service/microcloud.go
- microcloud/service/microovn.go
- microcloud/service/service_handler.go
Adds MicroOVN support.
All this really took was a copy/paste of `services/microceph.go` to `services/microovn.go` with the names changed. The default port for MicroOVN will be `:6443`
Also reworked the MicroCeph proxy to be a more general MicroCluster proxy, expecting a service name and a state directory.
> MicroOVN support

- microcloud/cmd/microcloud/add.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloudd/main.go
- microcloud/service/service_handler.go
Closes #32
Properly notifies the user of `init` and `add` that the server may be missing services. By default (i.e. `--auto`) we will continue anyway. 
In the event that a peer detected over mDNS is missing a service, it will be ignored.
> Notify missing services

- microcloud/service/service_handler.go
This allows for LXD to perform its initial startup, generate certificate, ... prior to MicroCloud needing it, making the bootstrap process much faster on slow systems.
> lxd: Wake up on initial startup

- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
Also adds `source: lxd_remote` on the remote storage pool when adding a peer, even though it's currently not handled properly on the LXD side.
> Fix MicroOVN config

- microcloud/api/services.go
- microcloud/cmd/microcloud/add.go
- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/selection_table.go
- microcloud/mdns/lookup.go
- microcloud/mdns/mdns.go
- microcloud/service/lxd.go
- microcloud/service/service_handler.go
Closes https://github.com/canonical/microcloud/issues/34
Closes #35
Closes #74
* By default, all uninitialized machines will now broadcast their info using every network interface.
The mDNS lookup requires checking against the `service`(`_microcloud`) field of the mDNS broadcast, and overlapping requests will block each other, making the lookup very slow. To remedy this, there is now a `ServiceSize` constant that will be used to generate as many `service` variations, before falling back to overlapping. The constant is currently set to 10, with a lookup performed every 100ms (so 1s for a whole lookup of up to 10 addresses on each peer). 
* On init, the user will be prompted to select from an updating list of available systems. By default this list will only show results in the same subnet. …
> Clustering by subnet & selectable peers

- microcloud/cmd/microcloud/main_init.go
- microcloud/service/lxd.go
Just found (and fixed) a bug where if `MicroOVN` doesn't exist, `MicroCloud` doesn't properly create the `lxdfan0` network on all peers.
> Apply network to all peers without OVN

- doc/.sphinx/requirements.txt
Read the docs uses an older Python version that cannot deal with urllib3 v2.0.
> doc: fix version error

- microcloud/cmd/microcloud/ask.go
- microcloud/service/lxd.go
I'm still not able to replicate the `no auth secret in response` error, but one potential cause may be the `GetServer` on every call to LXD. 
In order to get that error, it means we're sending a request that isn't going through the proxy specified to `ConnectLXD` for whatever reason. Since every call from MicroCloud does this, that means it might be something internal in LXD like this `GetServer` call.
> Skip GetServer on calls to LXD

- microcloud/cmd/microcloudd/main.go
Closes #110
Whew, finally caught this one! 🎉
In the end, I still wasn't able to replicate it successfully, but by using a lot of `time.Sleep`, reordering the `snap install` to put `microcloud` in between `microceph` and `microovn`, and abusing `lxc snapshot` to freeze the daemons temporarily, I was able to replicate it often enough to track down the source. 
Turns out the issue was the goroutine that checks for when optional services (MicroOVN and MicroCeph currently) are available. If MicroCloud can't find these services, but then they suddenly appear before the daemon fully sets up, we were attempting to "update" the broadcast message, but it hadn't been set up yet, and so the `AuthSecret` would end up missing.
> Ensure AuthSecret before restarting broadcaster

- doc/.readthedocs.yaml
Apparently, paths need to be relative to the root directory, not the directory that contains the .readthedocs.yaml file.
> doc: adjust paths in .readthedocs.yaml

- microcloud/cmd/microcloud/ask.go
Changes the requirement for ceph to at least 1 disk per machine up to 3 machines, rather than at least 1 disk for every machine.
Additionally, adds prompts to the interactive init to confirm if users wish to continue setting up ceph or ovn if some systems don't meet the requirements and must be skipped.
> Allow skipping systems for ceph

- microcloud/mdns/lookup.go
CutSuffix was added in go1.20. The go module for microcloud specifies go1.18 so we should only use what is availabile in that go version.
Closes #132
> mdns: Replace CutSuffix with HasSuffix and TrimSuffix.

- .github/workflows/tests.yml
- microcloud/.golangci.yml
- microcloud/Makefile
- microcloud/api/services.go
- microcloud/api/services_proxy.go
- microcloud/cmd/microcloud/add.go
- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/selection_table.go
- microcloud/cmd/microcloud/sql.go
- microcloud/cmd/microcloudd/main.go
- microcloud/mdns/lookup.go
- microcloud/mdns/mdns.go
- microcloud/revive.toml
- microcloud/service/lxd.go
- microcloud/service/lxd_join.go
- microcloud/service/microcloud.go
- microcloud/service/microovn.go
- microcloud/service/service_handler.go
- microcloud/test/lint/negated-is-bool.sh
- microcloud/test/lint/newline-after-block.sh
- microcloud/test/lint/no-oneline-assign-and-test.sh
- microcloud/test/lint/no-short-form-imports.sh
Adds `golangci-lint` and `revive` (to ensure comments on exported methods defined against unexported receivers). Also adds a number of custom linters that we use in lxd and lxd-cloud. 
I've added a "Code tests" job to the tests workflow. We can add unit tests there once we've added tests.
Also see https://github.com/canonical/microcloud/pull/133#issuecomment-1625127507
> Adds go linters and lint workflow

- microcloud/cmd/microcloud/main_init.go
Fixes a bug where only peers that added disks to `microceph` would create a pending remote storage pool. Now all peers will create the pending remote storage pool if any disks across all peers are added to `microceph`.
It's not too pretty but this will be refactored out by #138 soon anyway.
> microcloud/cmd/microcloud/main/init: Apply remote pool to all peers

- microcloud/api/services_proxy.go
Closes #140 
Looks like this started happening due to https://github.com/golang/go/commit/312920c00aac9897b2a0693e752390b5b0711a5a#diff-58d1202218e4b5db623ceb4abddb3c166adc4c34a327c1c9df106191edc370d2R589-R590
Instead of using the whole path, this changes the proxy to use the unix socket filenames in keeping with how LXD does it.
> microcloud/api/services/proxy: Don't use whole path for request URL

- microcloud/cmd/microcloud/main_init.go
- microcloud/service/lxd.go
- microcloud/service/service_handler.go
Adds a hook that restarts LXD on uninitialized MicroCloud systems when MicroCloud starts.
I'm not sure if immediately calling `GetServer` like I'm doing here will cause issues on slower machines, it seems to work fine on my machine.
This still has the caveat of requiring a `snap restart microcloud` to force LXD to restart. I'm open to also putting this restart on run on an execution of `microcloud init` although I'm concerned that have some odd effects on slower machines again.
> Restart LXD on MicroCloud start to refresh symlinks

- microcloud/cmd/microcloud/selection_table.go
Fixes an issue where artifacts would be shown in the table, and in rare occasions the whole table would be drawn incorrectly.
The issue was that the `go-survey` package we use for the selectable table does not re-compile the table template, instead pulling them from a map keyed by the string value of the template. 
As @markylaing found, there is an `interface{}` type on `MultiSelect` that we can abuse to pass in our own data into the template. What this means is we no longer need a method to keep track of the data being passed into the template and template functions, so we can assign the template as soon as possible.
In order to still preserve the ability to pass in pre-checked values into the table, I've added a field on to the new `templateData` struct, which alongside the …
> Pass table data to template

- microcloud/cmd/microcloud/ask.go
Return an error if user does not confirm to continue with missing services.
Fixes #146
> cmd/microcloud: Fix user confirmation for missing services

- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/service/interface.go
- microcloud/service/lxd.go
- microcloud/service/microceph.go
- microcloud/service/microcloud.go
- microcloud/service/microovn.go
Relies on #138 
his modifies the cluster join logic of MicroCloud to issue a token and instruct a system to join the cluster sequentially, one peer at a time.
This slightly slows down the join process but makes it more resilient as one node will not be overwhelmed with too many token requests, and then each join token won't have only the issuer's address as the target of the join request.
When there are 7 or more nodes left, MicroCloud will fall back to the old concurrent style of joining which issues all tokens for all systems at once, then concurrently instructs them all to join. After 7 peers, we should begin to see spare roles so there is less of a chance of role turnover blocking the cluster completely.
> Sequentially join the cluster

- doc/how-to/preseed.yaml
- microcloud/cmd/microcloud/add.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/cmd/microcloud/preseed_test.go
> Preseed yaml

- microcloud/service/microcloud.go
- microcloud/test/includes/microcloud.sh
Perhaps due to a recent MicroCeph update, the system tests were failing
to create OSD pools, and OSDs themselves weren't displaying (even though
they were created). This seems to be because cleaning out
`/var/snap/microceph` and restarting the snap doesn't create the
`var/snap/microceph/current/run` directory which is used by
microceph.osd.
Additionally cleans up some redundant OSD removal calls.
> Fix MicroCeph reset in system tests

- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/cmd/microcloud/preseed_test.go
- microcloud/test/suites/preseed.sh
If no part of the OVN configuration is specified, MicroCloud should try to set up a FAN network instead. 
If even one system has a specified interface, or if uplink addresses are given, then MicroCloud will try to find defaults for the other systems and set up OVN.
> Preseed support fix for FAN networks

- doc/.wordlist.txt
- doc/custom_conf.py
- doc/how-to/contribute.rst
- doc/how-to/index.rst
- doc/reuse/links.txt
Based on what we have for LXD.
> doc/contributing: add a contribution guide

- .github/workflows/tests.yml
The snap build trigger will fail anyway because of the inaccessible secret. But its clearer to see it skipped.
> github: Skip snap build for pushes on branches from dependabot

- microcloud/Makefile
> Fix double check-unit target in Makefile

- microcloud/test/suites/basic.sh
The images used all include `curl` and pulling it explicitly cause slow `apt-get update` step that's not needed. The other cloud-config we have was already fixed to the same extent.
> test/suites/basic: don't explicitely pull `curl`

- microcloud/cmd/microcloud/add.go
- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/mdns/lookup.go
- microcloud/service/service_handler.go
- microcloud/test/includes/microcloud.sh
- microcloud/test/suites/preseed.sh
Additionally adds a `lookup_interface` key to the preseed so that can have the same behaviour.
> Specify lookup interface to mdns handler

- doc/how-to/snaps.rst
- doc/how-to/support.rst
We recommended using the edge channel, but now the default channels work, so we should recommend to use those.
> doc: remove recommendation of edge

- microcloud/mdns/mdns.go
- microcloud/service/service_handler.go
Lookup was recently updated to lookup mDNS records via a particular interface, but the mDNS broadcasts were always coming from the default interface, even when advertising a different interface, so the lookup would ignore these records as they aren't coming from an interface that it expected.
> microcloud/service: Properly broadcast available interfaces over those interfaces

- README.md
- doc/.custom_wordlist.txt
- doc/explanation/microcloud.rst
When not using MicroOVN, the Ubuntu fan is used instead - document the limitations.
> doc: add information about fan network

- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/cmd/microcloud/preseed_test.go
Closes #226 
Currently when directly specifying disks for ceph, MicroCloud will require all systems to specify a disk unless a filter is also specified. 
Instead, we should only require 3 systems to specify a disk, and only during bootstrap.
> Fix ceph disk validation

- doc/reference/index.rst
- doc/tutorial/get_started.rst
Make it clear that the tutorial uses less RAM than recommended, and that this should not be done in a production environment.
> doc: clarify RAM requirements in the tutorial

- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/service/lxd_config.go
- microcloud/test/includes/microcloud.sh
- microcloud/test/suites/add.sh
- microcloud/test/suites/preseed.sh
Introduces a new feature that allows users to specify the DNS servers for the UPLINK network during the MicroCloud initialization process. Previously, MicroCloud configured the instances to use the gateway IP as the DNS server by default. Now you can set these values interactively like so:
```bash
Specify the default DNS addresses (comma-separated IPv4 addresses) for this OVN network instead of using the default gateway address? (empty to skip): <COMMA_SEPARATED_IPV4_ADDR>
```
You can also add this behaviour in the preseed file like so:
```yaml
...
ovn:
ipv4_gateway: 10.1.123.1/24
ipv4_range: 10.1.123.100-10.1.123.254
ipv6_gateway: fd42:1:1234:1234::1/64
dns_servers: 10.1.123.1,8.8.8.8 # now we can add custom DNS addresses to the OVN network like so
```
> feat: Give option to specify custom DNS addresses for OVN uplink

- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/cmd/microcloud/preseed_test.go
- microcloud/service/lxd_config.go
- microcloud/test/includes/microcloud.sh
- microcloud/test/main.sh
- microcloud/test/suites/add.sh
- microcloud/test/suites/basic.sh
- microcloud/test/suites/preseed.sh
Adds a step in the interactive setup after selecting disks for MicroCeph that asks if the user also wants CephFS.
This is also included in the preseed support with a boolean flag in the `storage` section.
> CephFS support

- microcloud/service/lxd_config.go
If LXD doesn't have the corresponding schema extension for the source.wipe config key, MicroCloud will never ask the user if they want to wipe disks, but will still populate the config with a 'false' value, causing an error.
Instead, we can simply omit the key if it's false, and it will be implicitly considered false.
> microcloud/service: Only set source.wipe if user explicitly agrees

- microcloud/service/lxd.go
When [this](https://github.com/canonical/lxd/pull/12832) is merged, this PR adds the integration with MicroCloud. After that, all the created VM instances in a MicroCloud deployment should be able to be live migrated with no additional user settings.
> lxd: parametrize LXD with `instances.migration.stateful` set to `true`

- microcloud/cmd/microcloud/ask.go
- microcloud/test/includes/microcloud.sh
This PR does 2 things:
* Moves the DNS question to be after both the ipv4 and ipv6 questions. Right now it's in the middle, which feels awkward.
* Because of the above, when choosing the default DNS nameservers, we only have the user's chosen IPv4 address at that point. By moving the question to the end, we can include both the chosen IPv4 and IPv6 addresses by default.
> Use both IPv4 and IPv6 chosen addresses for default DNS addresses

- doc/.wordlist.txt
- doc/explanation/initialisation.rst
- doc/how-to/initialise.rst
- doc/how-to/preseed.yaml
- doc/tutorial/get_started.rst
Should be merged after #269 because I wrote it based on that.
Updates the docs for the newer features (cephfs and dns nameservers), and also mentions that the mDNS lookup list updates as new machines are found periodically.
> doc: Update docs for cephfs and dns nameservers

- microcloud/test/includes/microcloud.sh
- microcloud/test/suites/add.sh
- microcloud/test/suites/basic.sh
@simondeziel this should fix your issue
> Fix DNS nameserver env var in tests

- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/cmd/microcloud/main_init_test.go
I will rebase once #276 is merged, the only new commit here is [this one](https://github.com/canonical/microcloud/pull/277/commits/fba259c7c20688198732ea7783e41dc2486c7507).
> Network sanity checks

- microcloud/service/lxd.go
- microcloud/service/lxd_config.go
With the content interfaces in places in LXD to detect MicroOVN and MicroCeph, we don't need to restart LXD to pick them up anymore. 
However, if we don't restart, this breaks support for versions of LXD prior to 5.21 when the content interface was introduced. We can't directly fetch the snap version or the available interfaces of LXD due to the snap confinement, so the best I came up with was to hard-code `5.21` into MicroCloud, and compare it to the server version reported from `/1.0` in LXD. 
If LXD is not at least version 5.21, then we need to restart the LXD daemon to pick up MicroOVN and MicroCeph integration. Otherwise we can just expect it to be there.
> Only restart LXD if version is less than 5.21

- microcloud/test/includes/microcloud.sh
The reason for this style change is that it produces less debug (`set -x`) noise as we can see is this short example:
```
$ sh -x
$ setup=""
+ setup=
$ setup="${setup}
> foo"
+ setup=
foo
$ setup="${setup}
> bar"
+ setup=
foo
bar
$ 
```
Versus:
```
$ sh -x
$ setup=""   
+ setup=
$ setup=$(cat << EOF
> ${setup}
> foo
> EOF
> )
+ cat
+ setup=
foo
$ setup=$(cat << EOF
> ${setup}
> bar
> EOF
> )
+ cat
+ setup=
foo
bar
$ 
```
> test/includes/microcloud: don't use wrapper shell+cat heredocs for setup

- .github/workflows/tests.yml
- microcloud/test/includes/microcloud.sh
- microcloud/test/main.sh
Here are some boot time and memory usage for the **2nd boot** (1st one being ignored due to cloud-init does its thing) of a guest VM.
From:
```
Startup finished in 780ms (kernel) + 7.248s (userspace) = 8.029s 
graphical.target reached after 5.743s in userspace
```
```
root@u22:~# free -mt
total        used        free      shared  buff/cache   available
Mem:            3932          94        3614          16         222        3777
Swap:              0           0           0
Total:          3932          94        3614
```
To:
```
Startup finished in 522ms (kernel) + 2.729s (userspace) = 3.252s 
graphical.target reached after 2.709s in userspace
```
```
total        used        free      shared  buff/cache   available
Mem:            3932          82        3674          16         175 …
```
> Optimize for speed

- doc/how-to/initialise.rst
- microcloud/api/services.go
- microcloud/api/types/services.go
- microcloud/client/client.go
- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/cmd/microcloud/preseed_test.go
- microcloud/cmd/microcloudd/main.go
- microcloud/service/interface.go
- microcloud/service/lxd.go
- microcloud/service/microceph.go
- microcloud/service/microcloud.go
- microcloud/service/microovn.go
- microcloud/test/includes/microcloud.sh
- microcloud/test/main.sh
- microcloud/test/suites/basic.sh
Closes #145
This PR allows initializing a new MicroCloud with some nodes that have already set up MicroCeph or MicroOVN in the past. This can be useful if you already have a MicroCeph cluster for example, that you want to "upgrade" into a MicroCloud.
Just after confirming the list of systems to use for the MicroCloud, we will try to grab a list of cluster members from each system. The underlying microcluster package will either return the list or report that the database is not initialized. We will record the first list that we obtain for each of MicroOVN and MicroCeph, and if the list is either non-existent or identical across any other systems, we can try to reuse those clusters.
The reuse process basically amounts to asking the system that has an existing cluster to generate join …
> Reuse existing MicroCeph and MicroOVN clusters

- microcloud/service/lxd.go
Semver was being compared backwards, so LXDs younger than 5.21 weren't restarting.
I hate these -1,0,1 functions :(
> microcloud/service: Fix semver comparison

- cmd/microcloud/main_init.go
After https://github.com/canonical/lxd/pull/12571 was merged, these timeouts are no longer necessary to avoid the join process breaking. 
The 4 system tests should stress-test this enough to capture any issues with removing the timeouts.
> microcloud/cmd/microcloud: Remove dqlite role shift timeouts

- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_test.go
- service/lxd_config.go
Per the discussion in #277
It feels a little silly to do a bunch of relatively more complex stuff at runtime to fix something that can be fixed by a single source of truth at compile time.
> Fix hardcoded uplink

- client/proxy.go
- service/lxd.go
- service/microceph.go
- service/microcloud.go
- service/microovn.go
Should be merged after #259 
In response to reviews from #259, I've added some additional commits to update the microcluster dependency, fix contexts, and add 2 new helpers:
* `UseAuthProxy` which applies the auth proxy used to manage the API of other services to a microcluster `Client`. This is now used in place of manually applying the proxy all over the place.
* `AuthProxy` which returns the actual proxy implementation, so we can also reduce the duplication for LXD's client which is not the same structure as `microcluster`'s.
> Add helper for setting up MicroCloud proxy

- service/lxd.go
It looks in between merging the long list of PRs during the last hours we missed a dependency due to not rebasing the PRs.
https://github.com/canonical/microcloud/pull/287 removed the `net/url` import from the `service/lxd.go` file. This now causes build failures on `main`: https://github.com/canonical/microcloud/actions/runs/9647792769/job/26607464289
> Add missing net/url import

- .github/.jira_sync_config.yaml
.jira_sync_config.yaml is a configuration file to allow the creation of Jira issues when a particular tag (Jira) is assigned to the GitHub issue. It uses [`gh-jira-sync-bot`](https://github.com/canonical/gh-jira-sync-bot). The issues in Jira are grouped in a specific epic defined in the config file, but the parent epic can be changed without affecting the synchronization. The default issue type assigned in Jira is "Bug" but it can be changed assigning a different label (feature,improvement, investigation) to the GitHub issue.
`gh-jira-sync-bot` is available for all projects under canonical/*. It is a web service that receives webhooks from GitHub that are provided as part of installation of GitHub App. Once service is triggered it will call Jira RestAPI endpoints to create/modify issues. …
> github: added .jira_sync_config.yaml for the synchronization with Jira

- doc/how-to/preseed.yaml
The preseed yaml file used as an example in the [docs](https://canonical-microcloud.readthedocs-hosted.com/en/latest/how-to/initialise/#howto-initialise-preseed) does not include the option 'lookup_subnet'. 
As this preseed example closely aligns with the [get started guide](https://canonical-microcloud.readthedocs-hosted.com/en/latest/tutorial/get_started/) `eth1` was changed  to `enp6s0` to avoid confusion with the device name added to the VM.
Not included in this PR, as I cannot find additional information on the behavior, is  `reuse_existing_clusters` which is also missing.
> Include 'lookup_interface' in preseed example and Use the correct ovn interface

- cmd/microcloud/ask.go
- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- mdns/lookup.go
- mdns/mdns.go
- service/lxd.go
- service/lxd_config.go
- test/includes/microcloud.sh
- test/suites/basic.sh
closes #159 
- This fix enable the detection for a cluster member for IPv6 support to set the appropriate flag for `hashicorp/mdns` to avoid panicking if IPv6 is not supported,
- This also contains a fix for avoiding an infinite timeout issue in the `lookupPeers` function.
- However, the mDNS query (without support for IPv6) being received by the other cluster member mDNS servers, whose the responses are well written back to the UDPv4 connection opened on the server, are not received by the client and the reason still remains a mystery...
> fix: don't panic when IPv6 is not supported

- service/lxd.go
- test/includes/microcloud.sh
As found by @masnax, masking journald services prevented booting after the initial/first boot.
> Fix boot issue

- cmd/microcloud/ask.go
- test/suites/basic.sh
- test/suites/preseed.sh
This is part of #332 too but since #334 is having issues with 24.04 VMs, I think it's worth merging now.
This makes it so that when disks are loaded for selection either internally during preseed/auto, or visually in a table with interactive setup, that they are sorted by their path, rather than the order that they appear in the list of resources fetched from LXD.
> cmd/microcloud: Force disk ordering by path name

- .github/workflows/tests.yml
- Makefile
- test/includes/check.sh
- test/includes/microcloud.sh
- test/main.sh
Despite the additional HW resources, the test run-times didn't improved drastically but hopefully this should be more robust. This should also open the door to doing heavier tests without running into space or RAM limits. The CPU overcommit ratio is also better thus reducing the steal time.
Test run-times can be compared with https://github.com/canonical/microcloud/actions/runs/9783672548/job/27012801592
Note: the [System (1.22.x, interactive)](https://github.com/canonical/microcloud/actions/runs/9783893557/job/27019237295?pr=334#logs) still takes ~3 hours and sometimes fail, same as with the regular runners :/
> github: run system-tests on larger runners (8cores+32G)

- cmd/microcloud/main.go
Makes it possible to redirect stdout as machine-readable (e.g. yaml) when `TEST_CONSOLE=1`
> cmd/microcloud: Print TEST_CONSOLE message to stderr

- .github/workflows/tests.yml
- cmd/microcloud/cluster_members.go
- doc/.wordlist.txt
- doc/how-to/index.md
- doc/how-to/recover.md
- test/includes/microcloud.sh
- test/main.sh
- test/suites/recover.sh
Implements cluster recovery with the same set of changes described in https://github.com/canonical/microcluster/pull/149
- I added another suite in the github workflow while I was working on tests; I don't feel like it fits well with any of the [existing test groups](https://github.com/canonical/microcloud/blob/main/test/main.sh#L175-L202) except `basic`, and `basic` already takes ~1hr to run. Not sure what is preferred here.
- Dqlite spellcheck; https://github.com/canonical/sphinx-docs-starter-pack/pull/252
Fixes #291 
LXD-1118
> Cluster recovery

- cmd/microcloud/add.go
- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- test/includes/microcloud.sh
- test/suites/add.sh
- test/suites/basic.sh
- test/suites/preseed.sh
Now that we are properly sorting disks, we can reliably validate that the disk ID we expected is the one that was selected automatically.
> test/includes: Add back specific disk validation

- cmd/microcloud/add.go
- cmd/microcloud/ask.go
- cmd/microcloud/cluster_members.go
- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- cmd/microcloud/main_init_test.go
- service/lxd.go
- service/lxd_config.go
- service/system_information.go
- test/includes/microcloud.sh
It was getting very hard and inefficient to modify or extend the MicroCloud setup logic without devolving into lots of temporary maps and slices, and redundantly calling back over the network to the other systems to fetch their configuration.
This PR attempts to address that by immediately collecting all relevant system information for the cluster setup in a `SystemInformation` for each system. Each question helper can then reference the fields and methods of the `SystemInformation` to check what is and isn't supported, rather than fetching them over the network each time.
In order to pass around `SystemInformation` as well as other common state information that were previously passed directly as arguments to each function, this PR also adds an `initConfig` type, of which all question …
> Collect system information prior to asking any questions

- api/services.go
- api/services_auth.go
- api/services_cluster.go
- api/services_tokens.go
- client/client.go
- cmd/microcloud/main.go
- cmd/microcloud/main_init.go
- cmd/microcloud/remove.go
- cmd/microcloudd/main.go
- doc/.custom_wordlist.txt
- doc/how-to/index.md
- doc/how-to/remove_machine.md
- service/interface.go
- service/lxd.go
- service/microceph.go
- service/microcloud.go
- service/microovn.go
- service/service_handler.go
- test/main.sh
- test/suites/basic.sh
`microcloud remove <name>` will now remove the given cluster member from all services. If `--force` is specified, it is also propagated to all services.
Since the clusters may not have all the same members, we do not error out if some services don't have the corresponding cluster member, instead we will log this as a warning and continue attempting to remove the cluster member from other services.
If no service has the cluster member, then we will error out, reporting that we couldn't find the cluster member across any services.
LXD will be attempted first, as it depends on the other ones. Then we concurrently try to remove the system from MicroCloud, MicroOVN, and MicroCeph.
> Add service-wide cluster member remove command

- cmd/microcloud/add.go
- cmd/microcloud/ask.go
- cmd/microcloud/main.go
- cmd/microcloud/main_init.go
- cmd/microcloud/services.go
- doc/how-to/add_service.md
- doc/how-to/commands.md
- doc/how-to/index.md
- service/lxd.go
- service/microcloud.go
- test/includes/microcloud.sh
- test/suites/basic.sh
Closed the old PR to start fresh.
Adds two new commands:
* `microcloud service list` will list the cluster members for every installed service, or report if it is not initialized. This will effectively be the same as calling all of the following in succession:
```
lxc cluster list
microcloud cluster list
microceph cluster list
microovn cluster list
```
The information shown will be the name, address, dqlite role, and current status of each member.
* `microcloud service add` will try to setup MicroOVN and MicroCeph on all existing MicroCloud cluster members, optionally setting up storage and networks for LXD. This is useful if MicroOVN or MicroCeph was at one point not installed on the systems and skipped during `microcloud init`. LXD and MicroCloud itself are required to already be set …
> `service add` and `service list`

- test/lint/capitalize-errors.sh
Quick and dirty but hopefully will save some time.
> test/lint: Add a check for error messages starting with lower case

- cmd/microcloud/add.go
- cmd/microcloud/ask.go
- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- test/includes/microcloud.sh
- test/suites/add.sh
- test/suites/basic.sh
If storage & networks have not been set up on existing cluster members, `microcloud add` should try to set them up for both new cluster members and old ones. 
This can be accomplished by simply populating the `InitSystem`s for all existing cluster members.
This also simplifies `setupCluster` because it no longer has different behaviour based on the `bootstrap` flag being set on `initConfig`. 
---
Some other cleanup:
* The profile update question has been moved to before cluster formation because the flow is awkward when the user has to wait a few minutes and then gets asked another question before the setup continues. 
* Standardizes ellipses in messages to be of the form `text ...`
> Fix `microcloud add` storage & network questions

- cmd/microcloud/ask.go
- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- cmd/microcloud/preseed_test.go
- test/includes/microcloud.sh
- test/main.sh
- test/suites/add.sh
- test/suites/basic.sh
Depends on #367 
Allows setting up remote `ceph` storage with fewer than 3 systems supplying disks.
With interactive init, when selecting disks for Ceph, a warning will be displayed indicating the setup is not fault-tolerant:
```
Disk configuration does not meet recommendations for fault tolerance. At least 3 systems must supply disks.
Retry selecting disks? (yes/no) [default=yes]:
```
After all members have joined the cluster, we verify that the spread of OSDs is at least 3, and if it is not, then we update all pool sizes and set the default OSD replication factor. 
For preseed, both OVN and Ceph setup no longer require 3 systems. Some small changes were made to the disk filtering logic, namely that `find_min` will default to 1 for ZFS storage since we can verify that all systems supply …
> Allow OSD selection with fewer than 3 systems

- cmd/microcloud/add.go
- cmd/microcloud/ask.go
- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- cmd/microcloud/preseed_test.go
- cmd/microcloud/services.go
- test/includes/microcloud.sh
- test/main.sh
- test/suites/add.sh
- test/suites/basic.sh
Adds basic single-node support.
This adds an initial question to `microcloud init` asking if the user wants to set up just one node.
```
Do you want to set up more than one cluster member? (yes/no) [default=yes]: 
```
If the user enters `no`, the system will follow the ordinary setup with ZFS and OVN (or optionally a FAN network instead), but the user will not be prompted for a lookup subnet and will not be presented a list of systems.
MicroCeph will be skipped as we require 3 systems. 
The cluster can be grown after this point by using `microcloud add`.
TODO:
> Single node support

- test/includes/microcloud.sh
How microcloud_interactive calculates its output is not useful to the test logs and is incredibly verbose, making it hard to read the logs for the workflow.
Instead, we can just print the final output to stderr to see if there is a mistake
> test/includes: Clean up microcloud_interactive logs

- test/suites/basic.sh
See: https://github.com/canonical/lxd/issues/14025
> test/suites: Don't use FAN network in test suite

- api/services.go
- api/types/services.go
- cmd/microcloud/ask.go
- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- doc/explanation/microcloud.md
- doc/how-to/index.md
- doc/how-to/initialise.md
- doc/how-to/ovn_underlay.md
- doc/tutorial/get_started.md
- go.mod
- go.sum
- service/interface.go
- service/lxd.go
- service/microceph.go
- service/microcloud.go
- service/microovn.go
- service/system_information.go
- test/includes/microcloud.sh
- test/suites/add.sh
- test/suites/basic.sh
closes https://github.com/canonical/microcloud/issues/239
> feat: specify an ovn underlay network through MicroOVN

- doc/tutorial/get_started.md
> doc/tutorial: permanently disable all IP addresses on microbr0's parent

- cmd/microcloud/cluster_members.go
microcluster v2 supports changing addresses as part of recovery, so this is no longer a constraint.
> Update recovery comment for address changes

- .github/workflows/security.yml
This adds two jobs to our workflows. One uses Trivy to scan MicroCloud's dependencies and the other scans the snap.
> Trivy vulnerability scanning

- cmd/microcloud/main_init.go
- cmd/microcloud/main_init_preseed.go
- doc/how-to/preseed.yaml
- test/suites/basic.sh
- test/suites/preseed.sh
The logic for detecting the OVN underlay configuration for preseed was not correct, it was relying on `c.state` which contains the resources available and already set up on existing cluster members, as well as new cluster members. It is used in interactive setup to manage additional configuration being supplied to the existing systems.
In preseed, we don't populate it yet because we only want to apply the precise recipe that is defined in the preseed, and not change any other cluster information implicitly (in interactive setup we can ask the user). 
Additionally, the input parsing was not correct, since it expected a CIDR per system however the ovn encap configuration wants an IP.
So this addresses that by instead using the list of systems parsed from the yaml itself in `p.Systems`, and …
> Fix underlay configuration for `preseed.yaml`

- cmd/microcloudd/main.go
- service/microcloud.go
- test/suites/recover.sh
Microcluster supports it so we might as well pass it through. If we're able to configure this for the snap service as well it would let us sleep for less time in the recovery tests.
> Add `--heartbeat` to `microcloudd`

- cmd/microcloudd/main.go
Follow-up from #407 
200ms is somewhat arbitrary; we want to explicitly disallow 0 but still let fairly small values through for future use in the test suite.
> cmd/microcloudd: Set minimum heartbeat value

- api/session_join.go
- api/types/session.go
- cmd/microcloud/add.go
- cmd/microcloud/ask.go
- cmd/microcloud/join.go
- cmd/microcloud/main_init.go
- cmd/microcloud/preseed.go
- cmd/microcloud/services.go
- cmd/microcloud/session.go
- go.mod
- go.sum
- multicast/discovery.go
- service/interface.go
- service/lxd.go
- service/lxd_config.go
- service/microceph.go
- service/microcloud.go
- service/microovn.go
- service/system_information.go
- service/version.go
- service/version_test.go
- test/main.sh
- test/suites/basic.sh
Adds version enforcement to MicroCloud.
The `services` list used to keep track of the set of installed services is repurposed as a `map[types.ServiceType]string` which maps each installed service to the version it's installed at. Then, when validating the set of services when receiving a join intent, we also check that the versions match exactly.
When running any `microcloud` initialization command, we first compile the list of installed services, along with their versions, and check that they match the pre-defined minimum versions. For semantic versions like LXD and MicroCloud, we only check against the major and minor versions, so patch versions are acceptable. Patch versions must still match between initiators and joiners.
For MicroCeph, we parse out the ceph version. This is not a …
> Daemon version enforcement

- test/includes/microcloud.sh
- test/main.sh
- test/suites/basic.sh
The new `capture_and_join` pattern seems to ignore the exit codes returned by the microcloud commands, so we can't check if the command actually errored without reading the output. 
Instead, this stores the exit code from each command in a `code` file, which is then checked for `0` in `capture_and_join` before unblocking.
* Also updates the tests to use `5.21/edge` to catch regressions earlier.
* Also makes sure debug binaries are updated on subsequent test runs. This slows down the test suite slightly, but is quite helpful for local debugging, as you can just rebuild your binaries and run a single test again.
> Check microcloud exit codes

- .github/workflows/tests.yml
- test/includes/microcloud.sh
After https://github.com/canonical/lxd/pull/14149 got merged in LXD we should not anymore use `--accept-certificate` when using the token as the token itself already contains the fingerprint which is enough.
This currently leads to failures in the test suite, see https://github.com/canonical/microcloud/actions/runs/11324655287/job/31553675652?pr=425.
> Test: Don't use `--accept-certificate` when using token

- .github/renovate.json
- renovate.json
This is using the same structure as microcluster to disable renovate and to place the configuration inside of `.github/`
Closes https://github.com/canonical/microcloud/issues/279
> renovate: Move the file and disable

- README.md
I figured the README requires some more clarification after merging https://github.com/canonical/microcloud/pull/383 as you also have to run `microcloud join` on all the other machines if you don't want to setup MicroCloud on a single machine.
In addition this also gives the hint that you can now have a MicroCloud using a single machine.
> README: Clarify commands for deployment

- cmd/microcloud/ask.go
This fixes a small regression introduced with the snap version enforcement which now causes the list of services that are going to be joined to display their version instead of the name:
`Commencing cluster join of the remaining services (ceph-version: 19.2.0~git20240301.4c76c50-0ubuntu6.1; microceph-git: c76c1f5fe9, 24.03, 5.21.2)`
> Cmd: Use service type name instead of version

- cmd/microcloud/main_init.go
- service/lxd_config.go
Only sets the OSD pool sizes for the OSD pools that MicroCloud creates. Also updates the reserved `.mgr` OSD pool as it would be created with a lower replication factor after we set the default on setups with fewer than 3 OSDs. 
Additionally, we do not ever lower OSD pool sizes anymore. If an OSD pool has been manually set to a higher replication size, we will not lower it, only raise it from 1 or 2 to 3.
> Restrict OSD pool resizing to only MicroCloud managed OSD pools

- multicast/discovery.go
- multicast/discovery_test.go
- service/session.go
In one run of the unit tests on GH [an error surfaced](https://github.com/canonical/microcloud/actions/runs/11327243960/job/31497901025?pr=426) that has shown that subsequent starts of the responder might collide which each other if the connection hasn't yet been cleaned up successfully when cancelling the context.
By having a dedicated `StopResponder` func we can make sure that the underlying connection is closed before starting a new one.
As before with mDNS we now track the server in the session so we can close it when the session gets closed.
> Discovery: Have a dedicated `StopResponder` to not rely on the context

- cmd/microcloud/add.go
- cmd/microcloud/join.go
- cmd/microcloud/preseed.go
- cmd/microcloud/remove.go
- cmd/microcloud/services.go
- cmd/microcloud/shutdown.go
- cmd/microcloud/sql.go
- cmd/microcloud/status.go
- cmd/microcloud/tokens.go
I have seen [this](https://github.com/canonical/microcloud/actions/runs/11404169982/job/31732770512?pr=436) error multiple times now in the pipeline which indicates that the local microcluster daemon isn't yet ready and therefore hasn't yet setup its socket.
This PR puts a check in each CLI command to wait until the daemon is ready.
> Cmd: Wait for the local daemon to become ready

- cmd/microcloud/preseed.go
- cmd/microcloud/preseed_test.go
- doc/how-to/preseed.yaml
- test/suites/basic.sh
These keys were not properly used in MicroCloud, and so are being removed, rather than implemented.
Reusing existing clusters doesn't make a lot of sense for `preseed` mode because we can't ask the user how to resolve conflicts, and thus are forced to error out, outside of some narrow cases.
> Remove unused preseed key

- cmd/microcloud/join.go
The `--auto` and `--wipe` flags seem to be a left over of from the `init` command when crafting the skeleton for the new `join` command introduced with https://github.com/canonical/microcloud/pull/383.
This PR removes the flags that don't have any value for the `join` command.
> Join: Remove `--auto` and `--wipe` flag

- cmd/microcloud/input_test.go
- cmd/microcloud/selection_table.go
Lately we have sometimes seen panics in the pipeline when `TEST_CONSOLE=1` was set. See https://github.com/canonical/microcloud/actions/runs/11327243960/job/31497902525?pr=426#step:14:52947
This is related to the survey table's `Render()` which returns too early.
The PR adds a custom survey option that allows waiting for all the options to be set including the stdio one which causes a panic down the line when calling `table.Update()` shortly after render as stdout isn't yet configured.
> Table: Fix fast `table.Update` after `table.Render`

- cmd/microcloud/ask.go
- test/includes/microcloud.sh
- test/suites/basic.sh
- test/suites/recover.sh
Prints a message rather than a log when skipping local storage. I thought to avoid a question in this case because the immediate question is for remote storage, and a user may not have enough disks for both.
For OVN config, we do ask a question because FAN networks are being phased out and is not an ideal alternative to MicroOVN anyway. Now, if any systems are ineligible, we immediately ask if the user wants to abort setup. If they choose to continue, we fallback to a FAN network.
> Report if skipping local storage & ovn config

- .github/workflows/tests.yml
- doc/how-to/index.md
- doc/how-to/install.md
- doc/how-to/recover.md
- doc/how-to/snaps.md
- doc/how-to/support.md
- doc/how-to/update_upgrade.md
- doc/tutorial/get_started.md
- test/includes/check.sh
- test/includes/microcloud.sh
- test/main.sh
- test/suites/upgrade.sh
This PR adds MicroCloud upgrade tests from `1/stable` to `latest/edge` as well as for the MicroCeph, MicroOVN and LXD dependencies.
As there might be MicroClouds running on 22.04, the test suite is modified to allow specifying a `BASE_OS` that will be used when setting up the testbed. 
This allows running the new `upgrade` test suite for both 22.04 and 24.04.
To verify the upgrade we check the cluster status of MicroCloud and its dependencies after the upgrade. In addition some workload is deployed before the upgrade whose boot ID and network connectivity is checked afterwards.
Furthermore dedicated docs are now added for update and upgrade procedures.
> Upgrade: Add docs and tests

- cmd/microcloud/add.go
- cmd/microcloud/ask.go
- cmd/microcloud/main_init.go
Whilst the `--auto` features was present having `--address`, `--wipe` and `--encrypt` made sense to influence what is happening in the auto mode.
Now after the auto mode is gone those flags have to be removed too.
This is a leftover.
Automating those settings can be done by using the preseed support.
> CLI: Remove redundant flags

- test/suites/basic.sh
Sometimes cloud-init fails to install `ping` so try to install it manually as well.
> test/suites: Ensure ping is installed

- cmd/microcloud/main_init.go
Couple changes to reduce the frequency of the MicroOVN alarm clock errors.
* Ensure LXD is always bootstrapped last, so MicroOVN has time to breathe. 
* Ensure we try to create storage pools before networks, so MicroOVN has even more time to breathe.
> Mitigate ovn alarm clock errors

- cmd/microcloud/ask.go
- cmd/microcloud/preseed.go
- cmd/microcloud/session.go
* Corrects spacing for OVN underlay selection summary
* Corrects spacing for OSD selections if the recommended disks warning is rejected
* Mentions "OVN" in the underlay question
* Changes up the grammar of the system selection prompt
* Adds text feedback to the `preseed` command to display which systems are expected and give feedback once the initiator detects them, and vice versa. 
* Omits an extraneous ceph cluster network log that was showing up in the preseed command.
> Various print fixes

- cmd/microcloud/main.go
- cmd/microcloudd/main.go
- service/microcloud.go
- service/version_test.go
- version/version.go
Ideally, this should be merged after updating go module dependencies and finishing up the last few bugfixes.
> Release MicroCloud 2.1 LTS

- version/version.go
Use the same LTS versioning scheme as LXD and include the .0 patch number for LTS versions.
> Version: Set the .0 patch number for the 2.1.0 LTS

- .github/workflows/commits.yml
Adds a check for the target branch. Also uses SHA1 commit pinning for the CLA action.
> github: Refresh commits job from LXD's

- .github/workflows/tests.yml
- Makefile
- staticcheck.conf
- test/includes/microcloud.sh
- test/main.sh
This PR adds code coverage for unit tests and snap system tests.
> Tiobe Integration

- doc/reference/index.md
JIRA ticket: https://warthogs.atlassian.net/browse/LXD-2117
Now that MicroCloud can be configured with Ceph disaggregated nets and an OVN underlay, we need to tell the user that the number of required net interfaces is **at least** 2.
> doc: Add network requirement notes

- doc/reference/index.md
JIRA ticket: https://warthogs.atlassian.net/browse/LXD-2123
> doc: Add new MicroCloud logos in the reference page

- .github/workflows/tests.yml
To prevent spending to much CI time running code/system tests for doc only changes, this PR introduces another job which can identify changes made in the pull request.
The code tests (and their system tests dependency) are now getting executed only if there were changes made outside of the `doc/**` directory.
> github: Run code/system tests for non doc changes only

- .github/workflows/tests.yml
The dorny/paths-filter dependency looks to consult the GitHub API for a list of changed files when executing within a PR.
When running on the main branch it needs to have access to the actual repository.
This currently fails on `main` https://github.com/canonical/microcloud/actions/runs/11743704790/job/32717168492#step:2:18
> github: Checkout repo to identify changes on main branch

- .github/workflows/security.yml
This updates the Trivy workflow to cache the vulnerability database when the download is successful and, when it is not, use the latest cached database instead. Motivated by some failures seen on some recent runs: https://github.com/canonical/microcloud/actions/runs/11638102909/job/32412374433
> github: Use cache when DB download fails

- multicast/discovery_test.go
Looks the most recent version of the linter now picks up potential context leaks.
This PR addresses this.
> Multicast: Avoid leaking the context in tests (govet)

- cmd/microcloud/main_init.go
- cmd/microcloud/session.go
- cmd/microcloudd/main.go
- service/microcloud.go
- service/service_handler.go
Adds thread safe helpers to get/set the service handler address. 
The address is updated in `PostBootstrap` and `PostJoin` after the MicroCloud daemon is initialized.
> Update service handler address after init

- .github/workflows/security.yml
Updates the Trivy workflow to scan the `3/edge` and `2/stable` channels instead of just the `latest`.
Should need another update after the release of the LTS.
> github: Scan proper snap channels

- doc/custom_conf.py
- doc/how-to/update_upgrade.md
Link to https://canonical-microceph.readthedocs-hosted.com/en/latest/how-to/reef-upgrade/ is now https://canonical-microceph.readthedocs-hosted.com/en/latest/how-to/major-upgrade/ (using Intersphinx syntax `<microceph:how-to/major-upgrade>`).
> doc/howto: fix broken link to microceph docs

- doc/tutorial/get_started.md
For virtual machines setting the `name=eth1` property doesn't make any difference as the NIC naming inside of the VM is detached from that. 
As the device itself is already named `eth1` we don't loose any information on the host side.
> Doc: Remove redundant device 'name' property

- service/lxd.go
MicroCloud should configure the `instances.migration.stateful` and set it to `true` in case the server supports the `instances_migration_stateful`.
This fixes the check which was looking for `migration_stateful_default` instead.
> Service: Set corret name of `instances_migration_stateful` extension

- .github/workflows/security.yml
A github cache can not be updated using the same key, so instead we update using a different key each time but use the same key to restore it.
> github: Fix database cache update

- doc/.custom_wordlist.txt
- doc/how-to/initialise.md
- Replace `node` with `cluster member` for consistent terminology
- Add pre-initialisation requirements to follow install steps & prep for any FDE encryption
- Update the Note annotation in the disk encryption step to advise what to do if disk wasn't prepped
> doc/howto/initialise: Update initialise instructions

- doc/.custom_wordlist.txt
- doc/tutorial/get_started.md
- fix typo of `micro01`..`04` to `micro1`..`4` in several places
- fix typo of `microcloud init` to `microcloud join` in output for joining members
- use `cluster member` when appropriate
- simplify & clarify text
- reduce parentheses and future tense
- note that VMs should not be used in production
- remove mention of needing minimum 3 VMs
- update screengrabs of the init and join processes
> doc/tutorial: tutorial improvements

- service/lxd.go
Signed-off-by: Julian Pelizäus <julian.pelizaeus@canonical.com>
(cherry picked from commit 2f4342c98f4470bd27698fbeed8c5899d7f4e44a)
> Service: Set corret name of `instances_migration_stateful` extension (v2-edge)

- .github/workflows/tests.yml
This reverts commit 203e34eee5c60e00937cbe8200b4175b51388452 after we have switched back to the free runners.
> Revert "github: stop running weekly tests"

- test/suites/instances.sh
Prevent errors like https://github.com/canonical/microcloud/actions/runs/12029208869/job/33534087228?pr=469
> Test: Consistently use 2GiB for container root vol

- .github/workflows/tests.yml
- Makefile
Don't install dqlite from apt but instead build it from source when running the tests.
This is the same approach as in Microcluster.
> Add dqlite build step in Makefile

- cmd/microcloud/services.go
Fixes pipeline errors expecting the questions to always be in a preset order.
> cmd/microcloud: Do not iterate over a map for the questionnaire

- .github/labeler.yml
- .github/workflows/triage.yml
This replicates the auto-labeling of PRs that affect Documentation in the LXD repo. 
To add more automated labels aside from Documentation, update `.github/labeler.yml`. See [the version in the LXD repo](https://github.com/canonical/lxd/blob/main/.github/labeler.yml) for examples.
> docs: add docs triage workflow using labeler action

- .github/workflows/tests.yml
Fixes the change introducing a new group name in launchpad.
This also needs to be backported into `v(1|2)-edge`.
> github: Use correct group name when pushing to launchpad

- cmd/tui/asker.go
- cmd/tui/console.go
- go.mod
- go.sum
Closes https://github.com/canonical/microcloud/pull/547
The new version of `charmbracelet/x/ansi` has deprecated some funcs and consts.
> Go: Update `charmbracelet/x/ansi` and replace deprecated consts/funcs

- .github/.jira_sync_config.yaml
I changed  the 'components' element in .jira_sync_config.yaml configuration file for the synchronization with Jira. to allow filtering by 'MicroCloud' key
> github: update of .jira_sync_config.yaml

- .github/workflows/tests.yml
As per https://discourse.canonical.com/t/end-of-the-year-update-for-tiobe-tics-required-action-to-disable-tics-cicd-pipelines/4890
> github: Temporary disable TICS job

- cmd/microcloud/ask.go
Follow-up from #542 
Prevents an accidental double-tap of the spacebar from rejecting the entire passphrase.
Allows `a b  c d`
> cmd/microcloud: Allow multiple spaces between passphrase elements

- .github/actions/system-test/action.yml
- .github/workflows/tests.yml
- api/session.go
- api/session_join.go
- test/suites/basic.sh
This PR splits the rather complex matrix system test into three groups.
The system test code is moved into a repo local action which is leveraged by each of the groups.
See an example of the restructured tests workflow [here](https://github.com/canonical/microcloud/actions/runs/12318431330?pr=469).
In addition the "instances" suite is now executed also on the Canonical runners when the workflow is triggered by schedule.
> github: Use Canonical runners for scheduled system tests

- microcloud/cmd/microcloud/add.go
- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/mdns/lookup.go
- microcloud/mdns/mdns.go
- microcloud/service/lxd_config.go
- microcloud/service/service_handler.go
- microcloud/test/includes/microcloud.sh
- microcloud/test/suites/instances.sh
- microcloud/test/suites/preseed.sh
Includes the cherry picks from https://github.com/canonical/microcloud-pkg-snap/blob/4816c5e5bacbfa6c4a79267479fe1db6f88724ff/snapcraft.yaml#L102-L114 in the `v1-edge` branch.
> Candidate cherry picks (v1-edge)

- microcloud/Makefile
- microcloud/cmd/microcloud/ask.go
- microcloud/cmd/microcloud/main_init.go
- microcloud/cmd/microcloud/main_init_preseed.go
- microcloud/go.mod
- microcloud/go.sum
- microcloud/service/microceph.go
The OSD API was changed with reef, but there is a manual patch that makes it compatible with the quincy Go client.
https://github.com/canonical/microceph/blob/2bddc9d6280d903dcb52a993833e991873565550/microceph/api/disks.go#L163-L172
So we can use that instead to support both reef and quincy.
> microcloud/cmd/microcloud: Use quincy client package (v1-edge)

- service/system_information.go
When creating local and remote storage pools the list of disks should not contain any cdrom drive.
Fixes https://github.com/canonical/microcloud/issues/566
> Service: Exlude disks of type `cdrom`

- doc/tutorial/get_started.md
fixing signature mess in # #543
>  doc: microcloud tutorial; update get_started.md (II)

- test/includes/microcloud.sh
- test/suites/upgrade.sh
Found this whilst reviewing https://github.com/canonical/microcloud/pull/581.
To catch error more early in the process use the candidate channels instead of stable.
> test/suites/upgrade: Use the respective service's candidate channels

- doc/how-to/update_upgrade.md
* Clarify confusing wording that suggests that MicroCloud is completely inoperable if snaps are not in sync in all cluster members. It's only the control plane that is inoperable, not the data plane; MicroCloud will continue to function as before, but no configuration changes can be made. 
* Misc small updates for readability / grammar fixes.
> doc: clarify microcloud behavior when snaps are not in sync

- test/main.sh
- test/suites/instances.sh
This aims at catching the panic the occurs from time to time in the interactive test suite. See https://github.com/canonical/microcloud/actions/runs/12989749320/job/36223575544:
`Error: System "micro02" failed to join the cluster: Failed to update cluster status of services: Put "https://10.24.232.150:9443/1.0/services": EOF`
> Add daemon cleanup logging

- cmd/microcloud/ask.go
Fixes https://github.com/canonical/microcloud/issues/603
Fixes a situation in which multiple joiners might see a list of services appear using a different ordering.
> Cmd: Sort remaining services in joiners message

- doc/how-to/commands.md
- doc/how-to/index.md
- doc/how-to/shutdown_machine.md
- Add how-to on shutting down cluster members
- Add to nav sidebar
- Add link to "Work with MicroCloud" page
Thanks to @simondeziel for testing and the commands to override services start/stop sequence.
> doc: add how-to on safely shutting down a cluster member

- doc/how-to/update_upgrade.md
This PR adds a section in the [How to update and upgrade](https://canonical-microcloud.readthedocs-hosted.com/en/latest/microcloud/how-to/update_upgrade/) docs page to explain that instances can be left running during and update/upgrade but the storage/network services might briefly be affected. It also explains how to use cluster evacuate to migrate instances away before an update/upgrade, including live migration for pre-configured VMs, and how to use cluster restore to migrate them back afterward.
> doc: keep instances running during update/upgrade

- doc/custom_conf.py
Increasing the max rate limit timeout should help with linkcheck issues due to rate limits.
Increasing the number of retries for read timeouts.
(Same updates as in LXD repo: https://github.com/canonical/lxd/pull/14892)
> doc: increase linkcheck max rate limit timeout and retries

- cmd/microcloud/add.go
- cmd/microcloud/cluster_members.go
- cmd/microcloud/join.go
- cmd/microcloud/main_init.go
- cmd/microcloud/preseed.go
- cmd/microcloud/remove.go
- cmd/microcloud/services.go
- cmd/microcloud/session.go
- cmd/microcloud/shutdown.go
- cmd/microcloud/sql.go
- cmd/microcloud/status.go
- cmd/microcloud/tokens.go
- cmd/microcloud/waitready.go
- cmd/microcloudd/main.go
- cmd/tui/selectable_table.go
Presumably with the new version of [revive](https://github.com/mgechev/revive/releases/tag/v1.6.1) new rules got added which make sense.
This PR fixes the new warnings.
> Lint: Fix revive

- .github/workflows/tests.yml
This reverts commit 954597a9be759bf31116ae6456641f2925e2c26b.
This commit broke the TICS job, see https://github.com/canonical/microcloud/actions/runs/13220529278/job/36907299961
We don't run the TICS job on the Canonical runners and don't require any exception.
> Revert path valid for both GitHub and Canonical runners

- multicast/info.go
Don't falsely populate the subnet by using the regular address. Use the actual network address.
Before this was setting `10.1.2.3/24` as the `Subnet` but it should actually set `10.1.2.0/24`.
> Network: Populate the `NetworkInfo` with the right subnet address

- cmd/microcloud/ask.go
Fixes https://github.com/canonical/microcloud/issues/613
Fix the output of the OVN underlay selection to also use the new formatting scheme using the yellow and bold highlight color:
> CLI: Use new formatting scheme for OVN underlay selection

- test/includes/microcloud.sh
The test suite should hold the lxd, microceph, microovn and microcloud snaps to not cause unplanned refreshes during test execution.
This was observed in the pipeline every now and then and caused some of the daemons to be stopped out of nowhere which resulted in API endpoints returning EOF.
In the daemon logs this is clearly indicated by systemd stopping the respective service and starting it afterwards:
```
Feb 20 09:53:13 micro03 systemd[1]: Stopping snap.microcloud.daemon.service - Service for snap application microcloud.daemon...
Feb 20 09:53:13 micro03 systemd[1]: snap.microcloud.daemon.service: Deactivated successfully.
Feb 20 09:53:13 micro03 systemd[1]: Stopped snap.microcloud.daemon.service - Service for snap application microcloud.daemon.
Feb 20 09:53:16 micro03 systemd[1]: …
```
> Test: Hold all snaps to prevent unplanned refresh

- api/services_cluster.go
- api/status.go
- cmd/microcloud/main_init.go
- service/microceph.go
- service/microovn.go
This allows switching the used version of Microcluster without having to also bump the version of Microcluster in both MicroCeph and MicroOVN.
> Untangle deps to MicroCeph and MicroOVN

- .github/workflows/tests.yml
Merging https://github.com/canonical/microcloud/pull/631 introduced another regression because in order to pick up the cover files from the Canonical runners (during weekly test execution) the path still has to be aligned with the different directory structure.
The `/home/runner` path does not exist on the Canonical runners, see https://github.com/canonical/microcloud/actions/runs/13349891499/job/37285054247
The TICS job is looking at `${{ github.workspace }}/cover` to find the respective files.
> github: Use `github.workspace` variable for GOCOVERDIR

- README.md
- doc/custom_conf.py
- doc/explanation/microcloud.md
The v2-edge branch's docs Makefile already [points to the correct docs versions](https://github.com/canonical/microcloud/blob/v2-edge/doc/Makefile#L12) for each integrated repository, so I only needed to change the path in custom_config.py. I tested to make sure that it doesn't just change the URL from latest to v2-edge; it also changes the docs version shown. 
To test this in the [RTD preview](https://canonical-microcloud--655.com.readthedocs.build/en/655/):
- ~~Switch to the `v2-edge` version from the flyout at the bottom right.~~
- From the docs landing page, scroll down to **How to use this documentation** , where there are links to LXD, MicroCeph, and MicroOVN.
- Hover over those links and confirm that they now direct to `v2-edge` instead of `latest`. Unfortunately, due to the way …
> doc: use v2-edge paths for integrated docs (v2-edge)

- README.md
- doc/explanation/microcloud.md
Replaces a programmatic include of text from README.md with the direct content of the same text, with links fixed to support versioning (so they point to the selected version of the docs instead of always the latest version). Related to https://github.com/canonical/microcloud/pull/655 (for v2-edge)
> doc: replace include from README to improve versioning support

- doc/Makefile
- doc/custom_conf.py
Per @roosterfish suggestion at https://github.com/canonical/microcloud/pull/655#discussion_r1967186572, updated so that a PATH_PREFIX variable is set in the docs Makefile then used when building for RTD only.
This should make it easier to remember to update the PATH_PREFIX for new versions (at the same time as setting the correponding versions for LXD/MicroCeph/MicroOVN). Plus, we'll only need to change the Makefile instead of both the Makefile and custom_conf.py. Will add change to main also once if this is approved/merged.
> doc: use PATH_PREFIX in docs Makefile for RTD build (v2-edge)

- doc/Makefile
- doc/custom_conf.py
Follow-up for https://github.com/canonical/microcloud/pull/665
Sets a variable for the URL path prefix for versioned docs in docs Makefile. This way, both the Makefile and custom_conf.py don't need to be updated for new versions, only the Makefile.
> doc: use PATH_PREFIX in docs Makefile for RTD build

- .github/actions/install-builddeps/action.yml
- .github/workflows/tests.yml
When switching from dqlite PPA to manual build in https://github.com/canonical/microcloud/pull/513, the `dqlite` dep was already added in the list of build artifacts.
However in the TICS job the global `CGO_*` and `LD_*` flags have to be modified to point to the downloaded location instead as it's different from the build job.
The PR also adds a common `install-builddeps` action as in LXD to wrap the dep installation.
> GitHub: Fix TICS deps

- .github/workflows/tests.yml
This allows follow up steps (e.g. unit tests) to still be able to access the deps.
> github: Copy dqlite deps instead of moving them

- doc/custom_conf.py
- doc/index.md
1) Make the Ubuntu Discourse the default Discourse instance instead of the LinuxContainers instance
2) Explicitly set all titles for links created using the [relatedlinks Sphinx extension](https://github.com/canonical/canonical-sphinx-extensions?tab=readme-ov-file#related-links) (both Discourse links and general related links) rather than fetching at build, so that external sites' outages do not affect LXD builds. (Same as https://github.com/canonical/lxd/pull/15131)
> doc: update how related links extension is used

- doc/Makefile
- doc/index.html
`index.html` is auto-generated and is [required to be in docs root](https://blog.readthedocs.com/builds-without-index/) yet it wasn't committed. It also re-generates at every build, which was causing `make run` to auto-loop (since it watches for changes), so used `--ignore` for sphinx-autobuild to ignore it.
> doc: fix infinite loop for make run

- doc/custom_conf.py
To avoid read timeout issues (different from rate limit timeout), set `linkcheck_timeout` to `45` seconds. Default when unset is `30`.
> doc: update linkcheck_timeout from 30 to 45 seconds

- CONTRIBUTING.md
- doc/how-to/contribute.md
- doc/how-to/snaps.md
- doc/how-to/support.md
- doc/index.md
Also, the Snap Store Proxy was renamed to Enterprise Store Proxy.
> Avoid HTTP redirects for a few doc links

- test/e2e/.gitignore
- test/e2e/README.md
- test/e2e/main.tf
- test/e2e/run
- test/e2e/variables.tf
- test/e2e/versions.tf
This PR lays the foundation to deploy instances on a MicroCloud, run tests with those and finally tear them down.
The tests themselves will be added in subsequent PRs. The initial plan is to add connectivity and live migration tests.
> test/e2e: add script/Terraform recipe to test MicroCloud deployments

- doc/.sphinx/_integration/add_config.py
This enables the ability for the integrated docs sets (LXD, etc) to use the `only` directive to show certain content only when a part of the MicroCloud integration. This is intended for use in showing `Note`-style annotations that indicate when a page in the integrated docs set is not relevant for MicroCloud users, such as [LXD's how-to guide on installation](https://github.com/canonical/lxd/pull/15266/files#diff-1d71fbf6452c615eacc9abfd4951cbf726383a79ac5796fb8c21be4b79d49ca2). Also see: https://github.com/canonical/lxd/pull/15266
> doc: add 'integrated' project tag to integrated docs sets

- service/service_handler.go
When requesting tokens for an invalid service name, MicroCloud panics as the API handler doesn't perform validation of the URL parameter
`POST /1.0/services/foo/tokens` -> panic
To fix this the generation of service handlers now errors out when trying to create a service handler for an invalid service type.
> Service: Fix panic for invalid types

- .github/actions/system-test/action.yml
We already build the MicroCloud binary with our own version of dqlite. This step is not required anymore and was missed when swichting the build process.
> github: Remove unsed step that installs dqlite dev

- doc/how-to/initialize.md
- doc/reference/requirements.md
The page was moved upstream in https://github.com/canonical/microceph/pull/542.
> doc: Fix link to Ceph disk encryption setup

- doc/how-to/install.md
Fixes the outstanding doc error in https://github.com/canonical/microcloud/pull/437 and closes the PR.
Fixes https://github.com/canonical/microcloud/issues/410
Closes https://github.com/canonical/microcloud/pull/437
> doc: Add documentation note for when LXD 5.0 is already installed

- test/main.sh
Whilst trying to reason about the recent test failures in the e2e suite, there was [this error](https://github.com/canonical/microcloud/actions/runs/14612411462/job/41100534644?pr=752) which made me wonder if LXD/MicroOVN isn't yet fully ready which might be indicated by a log entry in the LXD/MicroOVN log. 
This PR ensures that on failure the logs from all services (not only MicroCloud) are collected for all the `micro*` nodes.
> test: Collect the logs from all services on failure

- doc/custom_conf.py
The move to documentation.ubuntu.com/microcloud is approved and is done through the ReadTheDocs dashboard (by adding it as a subproject of the Ubuntu documentation library project). This PR updates the Sphinx custom_conf.py to reflect the change in URL and needs to be done along with the move. Otherwise, static resources won't fetch correctly.
> doc: update config for move to documentation.ubuntu.com

- doc/reference/requirements.md
Fixes #721 
Notes that the default storage filesystem type is ZFS.
> doc/reference/requirements: document default storage filesystem type

- .github/actions/system-test/action.yml
This is copied from https://github.com/canonical/lxd-ci/pull/460.
The error also happened in the MicroCloud CI, see https://github.com/canonical/microcloud/actions/runs/14859104409/job/41719518751.
> GitHub: Avoid early failure in detecting br_netfilter kernel mod

- doc/Makefile
- doc/custom_conf.py
Fix intersphinx links to point to /microcloud/v2-edge instead of /en/v2-edge per recent changes to site.
Backport of https://github.com/canonical/microcloud/pull/764
> doc: fix intersphinx links (v2-edge)

- CONTRIBUTING.md
- README.md
- doc/.sphinx/_integration/add_config.py
- doc/README.md
- doc/custom_conf.py
- doc/how-to/recover.md
- doc/how-to/support.md
- test/e2e/run
This PR updates absolute links to both the MicroCloud and LXD documentation due to both recently changing URLs to remove /en/ from the path and, in MicroCloud's case, moving to a subdirectory of documentation.ubuntu.com.
> Update absolute docs links

- .golangci.yaml
- Makefile
- api/services_auth.go
- api/services_proxy.go
- api/session.go
- api/session_join.go
- client/client.go
- client/proxy.go
- cmd/microcloud/ask.go
- cmd/microcloud/main_init.go
- cmd/microcloud/preseed.go
- cmd/microcloud/preseed_test.go
- cmd/microcloud/services.go
- cmd/microcloud/session.go
- cmd/microcloud/status.go
- cmd/microcloud/status_test.go
- cmd/tui/console.go
- cmd/tui/console_test.go
- cmd/tui/handler.go
- cmd/tui/selectable_table.go
- multicast/discovery_test.go
- service/lxd.go
- service/lxd_join.go
- service/microceph.go
- service/microcloud.go
- service/microovn.go
- service/system_information.go
- service/version.go
- service/version_test.go
- version/version.go
Only `revive` is missing from the linters list use by LXD. I kept it for another day ;)
> golangci-lint: enable perfsprint, prealloc and testifylint linters

- doc/explanation/networking.md
- doc/how-to/commands.md
- doc/how-to/shutdown_machine.md
- test/e2e/README.md
Per recent discussions, we recently updated wording in the LXD docs referring to moving instances between LXD servers to consistently use the term 'migrate' (see: https://github.com/canonical/lxd/pull/15575). This PR does the same for MicroCloud, including updating a reference target (`move-instances` to `howto-instances-migrate`) that was changed in LXD and is referenced in MicroCloud.
> doc: update move wording to migrate

- doc/how-to/snaps.md
- doc/how-to/support.md
- doc/how-to/update_upgrade.md
Update EOL for track 1 notice to past tense since it is now past the end of April 2025.
> doc: update EOL notice for track 1

- .github/workflows/tests.yml
- service/version.go
- service/version_test.go
Fixes https://github.com/canonical/microcloud/issues/670
Furthermore this extends the test matrix to also include LXD version 6.
> Service: Allow MicroCloud to be used with LXD 5.21 or newer

- doc/custom_conf.py
Adds sphinx-sitemap extension to generate sitemap.xml for SEO purposes. This is in response to a documentation-team-wide request that applies to all public-facing RTD documentation sets.
> doc: add sphinx-sitemap to generate sitemap for SEO

- doc/how-to/update_upgrade.md
This PR:
- Clarifies that evacuating running instances is not necessary for LXD snap refreshes.
- Emphasizes and further explains why LXD snap updates should be run in parallel, rather than in sequence like the other snaps for MicroCloud.
Closes https://github.com/canonical/microcloud/issues/649
> doc: clarify lxd refresh process

- cmd/microcloud/ask.go
- cmd/microcloud/preseed.go
- cmd/microcloud/session.go
- cmd/tui/handler.go
- cmd/tui/selectable_table.go
- cmd/tui/style.go
- service/lxd.go
- service/version.go
Fixes https://github.com/canonical/microcloud/issues/797
The reason for this PR is to be more cautious with colors in the new tui. 
We are using three central colors green, yellow and red to indicate:
* green: positive security related aspects (fingerprints, steps, passphrase)
* yellow: warning messages
* red: error messages
Especially user provided input should not be repeated using the warning color to not confuse the user and to really make warnings and errors stand out.
The new tui styling allows highlighting input using bold text which already is enough as it stands out from regular text.
In addition the way we output errors and warnings is now consistently performed through dedicated functions.
Furthermore we use our own asker (not anymore the one from LXD) so we can influence the …
> CLI: Use consistent colors

- doc/.custom_wordlist.txt
- doc/Makefile
- doc/custom_conf.py
- doc/how-to/install.md
- doc/how-to/snaps.md
- doc/how-to/support.md
- doc/how-to/update_upgrade.md
- doc/reference/index.md
- doc/reference/releases-snaps.md
- doc/reference/requirements.md
- doc/substitutions.yaml
- doc/tutorial/get_started.md
This PR:
- Adds a new Releases and snaps reference page, similar to the recently added LXD documentation [Releases and snap](https://documentation.ubuntu.com/lxd/latest/reference/releases-snap/) page. Updates/adds links to this page from other pages.
- Enables use of a sustitutions.yaml file similar to LXD's for facilitating documentation updates of the current LTS and feature tracks for MicroCloud.
- Moves the information about holding and synchronizing updates from the Manage the snap page to the Updates and upgrades page.
- Improves and adds to the Manage the snap and Updates and upgrades how-to guides.
- Updates the How to get support guide to align with LXD's [how to get support guide](https://documentation.ubuntu.com/lxd/latest/support/).
- Updates the How to install MicroCloud …
> doc: update snaps and releases documentation

- doc/.sphinx/spellingcheck.yaml
Anchor titles for intersphinx links (in the form of `<a ... title="in MicroCeph vv19.2.0-squid">`, for example) are affected by what other documentation sets put as the `Version` in their `objects.inv` metadata. This can cause spellcheck to fail, as seen [here](https://github.com/canonical/microcloud/actions/runs/15992724155/job/45109080075).
This PR prevents anchor titles from being checked in spellcheck, so that we don't have to spellcheck what intersphinx pulls into that title. Anchor titles are rarely used and this should have little to no impact otherwise.
> doc: ignore anchor titles in spellcheck

- doc/explanation/microcloud.md
This is a follow up on https://github.com/canonical/lxd/pull/15918.
> doc: Link to custom volume attachment constraints for local storage

- doc/.custom_wordlist.txt
This reverts one of the commits in https://github.com/canonical/microcloud/pull/839 as the links are now skipped generally.
> Revert "doc: add vlatest to custom wordlist"

- cmd/microcloud/ask.go
- cmd/microcloud/preseed.go
- cmd/tui/handler.go
- test/suites/instances.sh
Not configuring the gateway on the uplink configures an OVN network without external connectivity.
Whilst that might be a valid use case, currently this is not really supported in LXD as you have to provide an uplink network even though it's not used.
Until this is supported in LXD, we simply don't allow this type of configuration.
Furthermore the asker's error message printer is modified to allow passing underlying errors to the user for better understanding why an input might be invalid.
> CLI: Reject setup in case uplink network's gateway isn't set

- cmd/microcloud/preseed.go
- test/suites/preseed.sh
In preseed mode in case only an IPv6 gateway is set on the uplink, instead of the actual address MicroCloud was checking the IPv4 gateway (bug).
This caused MicroCloud not being able to configure an IPv6 only gateway on the uplink when in preseed mode.
Furthermore another test case is added for this scenario.
> Preseed: Fix IPv6 only uplink

- doc/custom_conf.py
The sitemap URL scheme needs `/microcloud` to generate links correctly. Currently they are being generated like this:
```<loc>https://documentation.ubuntu.com/microcloud/latest/doc-cheat-sheet-myst/</loc>```
instead of
```<loc>https://documentation.ubuntu.com/microcloud/latest/microcloud/doc-cheat-sheet-myst/</loc>```
> doc: fix sitemap URL scheme

- cmd/microcloud/add.go
In case no new system got selected with the `init` subcommand, the questionnaire falls back to creating a single node MicroCloud. In case of the `add` subcommand, there has to be at least one new system to continue.
The check itself cannot be done inside the initiating session because the same session func is used for both the init and add subcommands.
> CLI: Exit `add` command in case no new system got selected

- cmd/microcloud/ask.go
When no disks are available, MicroCloud notifies the user that neither local nor remote storage can be configured. For remote storage this was displayed to the user through a warning. Local storage was using a log message which is not directly visible to the user.
This PR ensures that both local and remote storage configuration consistently use the same warning message in case the configuration get skipped:
```bash
root@micro01:~# microcloud init
Waiting for services to start ...
Do you want to set up more than one cluster member? (yes/no) [default=yes]: no
Using address 10.87.144.48 for MicroCloud
! Warning: Discovered non-LTS version "6.4" of LXD
Gathering system information ...
! Warning: No disks available for local storage. Skipping configuration
! Warning: No disks available for …
```
> CLI: Consistent warning when skipping storage

- cmd/tui/style.go
When cobra crafts an unknown command's help message, only the first line should use the prefix with error symbol:
Before such a message looked like this:
> CLI: Ensure a clean unknown command help message

- doc/.sphinx/_integration/add_config.py
- doc/custom_conf.py
- doc/how-to/recover.md
- test/e2e/run
This PR cherry-picks the following commits from `main` to v2-edge`:
* `9d17880` update absolute URL links to LXD docs
* `e5f96c2` doc: update config for move to documentation.ubuntu.com
* `125f226` doc: fix sitemap URL scheme
* `808f420` doc: add sphinx-sitemap to generate sitemap for SEO
A few manual edits were added to use URLs corresponding to the v2-edge docs version (e.g., `stable-5.21` instead of `latest` docs version for LXD)
> doc: backport config and URL updates (v2-edge)

- doc/.sphinx/build_requirements.py
Recent buggy update to canonical-sphinx-extensions causing build failures with "WARNING: more than one target found for 'myst' cross-reference" messages. This PR pins the extension to a previous version.
(cherry picked from commit 505495b64bb8e426f7834eab2809bff7b2b7d9c5)
> doc: pin canonical-sphinx-extensions version (v2-edge)

- cmd/microcloud/main_init.go
- test/suites/add.sh
- test/suites/basic.sh
- test/suites/preseed.sh
This fixes a bug when adding new systems to MicroCloud.
If the already existing MicroCloud only has local storage configured, you can decide to configure distributed storage when adding new systems.
In this situation the new systems haven't had their LXD `storage.images_volume` and `storage.backups_volume` settings configured due to a limitation which was setup by MicroCloud which either tracked new or existing pool's.
Another test is added to explicitly check this behavior.
Also a race when enabling optional services is fixed by adding a consequent restart of MicroCloud (see last commit).
> Storage: Fix backup and image vols for new systems

- .github/workflows/tests.yml
- test/main.sh
- test/suites/basic.sh
This allows getting faster test feedback.
Currently the `interactive` test suite runs for over 2h which is tedious.
The PRs finally splits tests into more granular suites.
> GitHub: Split tests into smaller suites

- cmd/microcloud/main_init.go
- test/includes/microcloud.sh
- test/suites/basic.sh
Preceded by https://github.com/canonical/microcloud/pull/864
The question to ask for profile device replacement was only applicable for networks because the storage section was missed when migrating the code into a helper in https://github.com/canonical/microcloud/commit/29764bcd6a4e54819a2a575f657970cfb7cc7f7a.
This had the effect that only in case distributed network got configured the question got asked to replace the FAN with OVN network.
However when configuring distributed storage the profile's root device got replaced in any case without asking the user.
Another check is added in this PR to explicitly check the behavior which went unnoticed when refactoring the code.
> CLI: Fix profile replacement for storage pools

- doc/how-to/add_machine.md
Before releasing 2 LTS the flag was already removed and it's a left over in the docs.
> doc: Remove notion about `--wipe`

- cmd/microcloud/ask.go
- test/includes/microcloud.sh
- test/suites/basic.sh
Preceded by:
* https://github.com/canonical/microcloud/pull/864
* https://github.com/canonical/microcloud/pull/863
Fixes https://github.com/canonical/microcloud/issues/812.
The PR ensures that an existing (configured) MicroCeph cluster can be reused by MicroCloud without the need of having to add additional disks during the process.
In a scenario with multiple nodes running MicroCeph, a user might decide to leverage the MicroCeph cluster which is already configured with OSDs for MicroCloud. MicroCloud allows this re-use and asks during the interactive questionnaire if the user wants to reuse this existing cluster.
However until now MicroCloud required to add additional disks (OSDs) to be able to include this existing cluster.
This limitation is now removed and the re-use of disks is made …
> Service: Allow distributed storage config without adding new disks

- doc/how-to/index.md
This PR reorders the navigation menu per discussion with @mseralessandri, in preparation for adding a Terraform how-to guide to this section. It also improves the introductory text (the first 200 characters of which is used for the meta description of the page).
A separate forthcoming PR will also rename the "Add a machine" "Remove a machine" and "Shut down a machine" guides to use "cluster member" instead of "machine" and group them under a "Manage cluster members" subsection.
> doc: reorder how-to guides navigation menu

- doc/how-to/snaps.md
- doc/how-to/update_upgrade.md
- doc/reference/releases-snaps.md
This PR fixes link targets that are intended to point to MicroCloud internal docs but are pointing at LXD's docs through intersphinx. Due to the link targets existing in LXD latest branch, the links did not raise an error, but the issue showed up in a [backport PR](https://github.com/canonical/microcloud/pull/893) where the LXD branch used in the backport (stable-5.21) does not yet have those link targets.
> doc: fix internal link targets

- .github/workflows/tests.yml
In one of the last scheduled weekly test runs I have observed that in case the last commit on main consists only of doc changes, it doesn't run the full test suite: https://github.com/canonical/microcloud/actions/runs/16545336169 This is due to the fact that we run only the resource intensive code and system tests for changes that actually affect this part of the code.
By making the check for except_docs dependent on the github.event_name, we can ensure that the code (and system) tests will always run regardless whether or not the last commit on main contains only doc changes.
> GitHub: Run scheduled tests fully also for doc only changes

- doc/explanation/initialization.md
- doc/explanation/microcloud.md
- doc/explanation/networking.md
- doc/tutorial/get_started.md
I audited the `relatedlinks` front matter in MicroCloud docs and added manual link text to the Wikipedia links that have recently been causing issues (see: https://github.com/canonical/microcloud/pull/945), as well as other links for prevention's sake. This should cause the build to quit failing from 503 HTTP responses on those links. 
I also removed a couple of `relatedlinks` that were linking to the default LXD documentation, as the LXD docs are already linked at the top of the MicroCloud site so another link is unnecessary (and could send them to the wrong docs version, since they went to the default/stable version, and the user could be clicking on it from the latest version).
> doc: fix breaking related links

- doc/explanation/initialization.md
- doc/explanation/microcloud.md
- doc/explanation/networking.md
- doc/tutorial/get_started.md
This backports https://github.com/canonical/microcloud/pull/946 and unblocks the builds.
> Backport broken related links (v2-edge)

- cmd/microcloud/ask.go
- cmd/microcloud/join.go
- cmd/microcloud/session.go
- cmd/tui/autocomplete.go
Fixes https://github.com/canonical/microcloud/issues/949.
We should not tell the user to verify the joiners fingerprint before this can actually be done on the initiator to avoid confusion.
Furthermore it fixes a few smaller inconsistencies in the new autocomplete tui model.
> Questionnaire: Improve flow for fingerprint verification

- doc/custom_conf.py
In the GitHub CI checks, the docs spellcheck test runs on a test build that uses the `SINGLE_BUILD` flag in MicroCloud's custom Sphinx configuration. This makes it so that the integrated repositories are not unnecessarily cloned for CI tests. However, this was pulling the `objects.inv` file (Sphinx's object inventory file used for intersphinx linking) from https://canonical-microovn.readthedocs-hosted.com/en/latest/objects.inv for both MicroCloud's `v2-edge` and `main` branches. The `latest` version is is the only ReadTheDocs version offered by the MicroOVN docs, and it sources from the MicroOVN repository's `main` GitHub branch.
MicroOVN recently changed a document, causing the spellcheck CI test to fail on MicroCloud's `v2-edge` only with …
> doc: fix microovn object inventory issue in CI build (v2-edge)

- doc/.custom_wordlist.txt
- doc/index.md
- doc/redirects.py
- doc/tutorial/index.md
- doc/tutorial/multi-member.md
- doc/tutorial/single-member.md
This PR sets up the Tutorials section of the MicroCloud documentation to offer a second tutorial that sets up a single-member cluster on a physical machine.
Like the existing tutorial that uses LXD VMs to create a virtualized sandbox envrionment for a multi-member MicroCloud cluster, this tutorial can be run using a single physical machine. However, unlike the existing tutorial, this provides a clearer mental model of how MicroCloud is set up in the real world. Having the only tutorial use VMs as cluster members can confuse the mental model for users who, regardless of any notices to the contrary, leave the tutorial with a perception that MicroCloud cluster members are intended to be VMs. That is only recommended for development/testing environments, and in real-world production …
> doc: add physical single-member cluster tutorial
