canonical/microcloud

microcloud/cmd/microcloud/main_init.go, microcloud/service/lxd.go, microcloud/service/lxd_join.go
Signed-off-by: Max Asnaashari <max.asnaashari@canonical.com>
=> microcloud/service/lxd/join: Join cluster without setting up trust first

microcloud/cmd/microcloud/main_init.go
Signed-off-by: Max Asnaashari <max.asnaashari@canonical.com>
=> microcloud/cmd/microcloud/main/init: Proxy to target for adding disks

snapcraft.yaml
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
=> snapcraft: Strip un-needed plugs on client

README.md
Signed-off-by: Ruth Fuchss <ruth.fuchss@canonical.com>
=> readme: small language fixes

doc/reference/index.rst
Signed-off-by: Ruth Fuchss <ruth.fuchss@canonical.com>
=> doc: add information on mixing architectures and growing a cluster

microcloud/cmd/microcloud/ask.go
=> microcloud/cmd/microcloud/ask: Add disk fallback paths

microcloud/cmd/microcloud/add.go, microcloud/cmd/microcloud/ask.go, microcloud/cmd/microcloud/main_init.go, microcloud/service/lxd.go
=> Ovn uplink network setup

microcloud/cmd/microcloud/ask.go
=> microcloud/cmd/microcloud/ask: Allow skipping IPv6 gateway

microcloud/cmd/microcloud/ask.go
=> microcloud/ask: Don't offer OVN if no uplink

microcloud/cmd/microcloud/ask.go, microcloud/service/lxd.go
LXD will automatically use an EUI64 address which is fine.
=> microcloud/init: Don't ask for IPv6 OVN range

README.md, doc/explanation/index.rst, doc/explanation/initialisation.rst, doc/explanation/microcloud.rst, doc/how-to/initialise.rst
Also split up the explanation section into separate pages.
=> doc: add more information to the docs

microcloud/cmd/microcloud/add.go, microcloud/cmd/microcloud/ask.go, microcloud/cmd/microcloud/cluster_members.go, microcloud/cmd/microcloud/main_init.go, microcloud/cmd/microcloud/selection_table.go, microcloud/cmd/microcloud/shutdown.go, microcloud/cmd/microcloud/sql.go, microcloud/cmd/microcloud/tokens.go
I haven't done any tests or Go validation or anything, but it should really only be changes to the strings. ;)
=> doc: language fixes for initialization prompts and help texts

microcloud/cmd/microcloud/cluster_members.go, microcloud/cmd/microcloud/tokens.go
=> Adds a format flag when listing tokens and cluster members.

microcloud/test/main.sh, microcloud/test/suites/preseed.sh
=> Preseed yaml test

doc/.wordlist.txt, doc/custom_conf.py, doc/how-to/index.rst, doc/how-to/snaps.rst, doc/reuse/links.txt
Based on
https://discourse.ubuntu.com/t/managing-the-lxd-snap-package/37214
=> doc: add information about managing the snaps

.github/workflows/tests.yml, microcloud/test/includes/check.sh, microcloud/test/includes/microcloud.sh, microcloud/test/main.sh, microcloud/test/suites/add.sh, microcloud/test/suites/basic.sh
=> Make tests `shellcheck` clean

.github/dependabot.yml, .github/workflows/tests.yml
Also enable dependabot while at it.
=> github: add commit signing and git fsck to build job

doc/.custom_wordlist.txt, doc/.sphinx/spellingcheck.yaml, doc/how-to/commands.rst, doc/how-to/index.rst
Include a command list, linking to LXD documentation for more information.
=> doc: add a cheat sheet for common commands

doc/.custom_wordlist.txt, doc/custom_conf.py, doc/how-to/install.rst, doc/how-to/snaps.rst, doc/reference/index.rst, doc/tutorial/get_started.rst
=> Various small doc updates

doc/tutorial/get_started.rst, microcloud/cmd/microcloud/ask.go, microcloud/service/lxd.go
Closes #230  
It's a bit hard to be descriptive, leave out OVN jargon, and keep the questions concise, but here's something a bit nicer.
=> Clear up network questions

doc/reuse/links.txt
Fix the MicroCloud documentation build
=> doc: fix broken links in documentation

doc/.custom_wordlist.txt, doc/explanation/microcloud.rst, doc/how-to/initialise.rst, doc/reference/index.rst, doc/tutorial/get_started.rst
Make it clear that you need an uplink network and two dedicated network interfaces for MicroCloud.
=> doc/networking: clarify how networking works

api/services.go
After the cluster has formed, the nodes should be in each others' truststore so we don't need to rely on the mDNS auth secret for communication anymore.
=> microcloud/api: Don't require mDNS secret for cluster members

doc/custom_conf.py, doc/doc-cheat-sheet-myst.md
Also remove some parts that would lead to build errors otherwise.
=> doc: include the MyST cheat sheet so it is published

cmd/microcloud/main_init_preseed.go, test/suites/preseed.sh
Presently, `lookup_subnet` in the [MicroCloud preseed](https://canonical-microcloud.readthedocs-hosted.com/en/latest/how-to/initialise/#non-interactive-configuration) is used to determine the listen address of the services running on the local member. 
Instead, this PR uses the first address assigned to `lookup_interface` that falls within the `lookup_subnet` to determine the listen address for the local services. 
Fixes #331
=> Fix lookup subnet

service/lxd.go, test/includes/microcloud.sh
Fixes #214 
I'd prefer to mark this ready for review and rebase to main once we've pushed Microcluster v2 so that the tests can appear happy, but if @masnax would like this merged sooner I can make that happen. Let me know.
=> Set core https address

test/includes/microcloud.sh
Follow up on https://github.com/canonical/microcloud/pull/383#discussion_r1792471944.
=> Test: Clarify comments on the interactive join funcs

cmd/microcloud/ask.go, cmd/microcloud/main_init.go, cmd/microcloud/preseed.go, doc/explanation/microcloud.md, doc/how-to/ceph_networking.md, doc/how-to/initialise.md, doc/tutorial/get_started.md, test/includes/microcloud.sh, test/main.sh, test/suites/add.sh, test/suites/basic.sh
JIRA ticket: https://warthogs.atlassian.net/browse/LXD-1808
=> ceph: Add support for Ceph public network seggregation

doc/how-to/initialise.md
minor notes to help on 
```
Insufficient number of disks available to set up distributed storage, skipping at this time    
```
it took me some time to realize i was allocating all my storage for local and had nothing left for distributed :D
=> docs: Update initialise.md

cmd/microcloud/main_init.go
Potential solution for #427 
Seems this isn't an issue with 22.04 necessarily, but with how we are using the microceph client. For the [`AddDisk`](https://github.com/canonical/microceph/blob/e32ad499ad83dcf6401891cc5739524bcdcd6dd4/microceph/client/disks.go#L18-L29) function, API side errors are compiled in `types.DiskAddResponse` instead of the error returned by the client function. 
As such, we were ignoring most disk-add errors. The reason this led to hangs is because we would proceed to create the LXD storage pools, which would hang forever on Ceph trying to create OSD pools without any OSDs. 
In particular, if encryption is requested, MicroCeph requires the following to be run before running `microcloud init`:
```bash
sudo snap connect microceph:dm-crypt
sudo snap restart …
```
=> Check MicroCeph for API errors

doc/tutorial/get_started.md
=> doc: Account for pre-installed LXD in the tutorial

doc/how-to/add_machine.md, doc/how-to/initialise.md, doc/how-to/preseed.yaml
JIRA ticket: https://warthogs.atlassian.net/browse/LXD-2124
* Add missing field in preseed YAML file.
* Add more explanations on what resources the Ceph networks are conveying.
=> doc/preseed: doc fixes in preseed file

doc/tutorial/get_started.md
=> doc/tutorial: Explicitly require LXD 5.21

doc/how-to/add_machine.md, doc/how-to/initialise.md, doc/how-to/preseed.yaml
This PR adds minimal preseed examples for both initialization and growing of a MicroCloud.
In addition the preseed reference file now lists all the required keys.
=> Doc: Add minimal preseed examples

api/status.go
=> Set proper address and name in status respose

doc/how-to/index.md
Previous order:
- How-to Guides
- Install MicroCloud
- Update and upgrade
- Manage the snaps
- Initialise MicroCloud
New order:
- How-to Guides
- Install MicroCloud
- Initialise MicroCloud
- Update and upgrade
- Manage the snaps
=> doc: move initialise docs higher up nav menu/toctree

doc/.custom_wordlist.txt, doc/how-to/install.md, doc/reference/index.md
Pre-deployment requirements including general requirements, testing/development requirements, and production requirements added to [How to install MicroCloud](https://canonical-microcloud.readthedocs-hosted.com/en/latest/microcloud/how-to/install/) docs.
=> doc/howto/install: add pre-deployment requirements

doc/how-to/install.md, doc/tutorial/get_started.md
This PR removes the old video showing outdated commands and adds the new one.
=> Doc: Replace video to showcase latest command sequence

doc/.custom_wordlist.txt, doc/reference/index.md
Updates to reference/index.md requirements sections with added information about:
- software versions to use
- FDE prerequisites
- number of cluster members for various environments
- VM vs physical machine for cluster members
- using distributed storage with a single member
- RAM minimum recommendation for production
- storage disk recommendation for production
- additional networking requirements
=> doc/reference: update requirements section in reference

cmd/microcloudd/main.go, service/lxd.go, test/includes/microcloud.sh, test/suites/upgrade.sh
=> Set `user.microcloud` when bootstrapping LXD

doc/how-to/commands.md
Fix incorrect use of inline formatting for a command.
=> doc: fix inline command format

.github/workflows/tests.yml, Makefile
Don't install dqlite from apt but instead build it from source when running the tests.
This is the same approach as in Microcluster.
=> Add dqlite build step in Makefile (v2-edge)

cmd/microcloud/preseed.go, test/suites/preseed.sh
Fixes a situation in which the `remote` storage pool cannot be created on LXD because MicroCloud only prepares the storage pool on nodes that supply a disk.
=> Preseed: Always create remote pools across all members

doc/tutorial/get_started.md
This should help clarify where IP addresses are coming from.
Fixes https://github.com/canonical/microcloud/issues/499
=> Doc: Used fixed IPs for the micro* VMs

.github/workflows/tests.yml
cherry picked from commit 2b3986b24a2d82037691c44a9fdeb7c60826b6d1
=> Backport using right launchpad group (v2-edge)

doc/how-to/install.md
- Per request from Field, added information about network requirements if using OVN underlay network
- Clarified networking requirements
- Clarified in Testing and Production tabs that they are in addition to the General requirements (rather than in place of)
=> doc: improve predeployment requirements

.github/workflows/security.yml
Closes https://github.com/canonical/microcloud/issues/565
=> github: Let trivy scan 1/stable

cmd/microcloud/ask.go, cmd/tui/handler.go, test/suites/basic.sh
Fixes https://github.com/canonical/microcloud/issues/521
Add a note that the uplink interface has to be in state UP.
Also use the same format for printing warnings as we do for printing errors.
=> Questionnaire: Clarify uplink interface error message

.github/actions/system-test/action.yml, .github/workflows/tests.yml, test/e2e/.gitignore, test/e2e/README.md, test/e2e/main.tf, test/e2e/reboot.local-lxd-vm, test/e2e/run, test/includes/microcloud.sh, test/main.sh, test/suites/basic.sh, test/suites/e2e.sh, test/suites/instances.sh
Here's an example (local) run:
```
$ DESTROY=no ./run mc
Using overrides from terraform.tfvars:
--------------------------------------
containers_per_host = 1
vms_per_host = 1
--------------------------------------
Setting up e2e environment on mc
terraform apply
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - terraform-lxd/lxd in /home/sdeziel/git/terraform-provider-lxd
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
data.lxd_info.cluster: Reading...
lxd_project.e2e: Refreshing state... [name=e2e-testing]
data.lxd_info.cluster: Read complete after 0s …
```
=> e2e-testing: connectivity and rolling reboot tests

test/e2e/README.md, test/e2e/reboot.local-lxd-vm, test/e2e/run, test/suites/e2e.sh
Improve documentation based on feedback from the first external users.
=> e2e tweaks

.github/actions/system-test/action.yml, .github/workflows/security.yml, .github/workflows/tests.yml, .github/workflows/triage.yml, doc/.readthedocs.yaml
Use latest LTS except in code/system tests.
=> Ubuntu 24.04 runners

cmd/tui/console.go, cmd/tui/handler.go, cmd/tui/selectable_table.go
- cmd/tui/handler: avoid panic at runtime due to trying to copy into an inner nil slice
see https://github.com/canonical/microcloud/actions/runs/15183238063/job/42697492228 for a failing test run due to panick at runtime
=> cmd/tui/handler: avoid panic at runtime due to trying to copy into an inner nil slice

cmd/microcloud/cluster_manager.go
* ensure app is initialized for any cluster manager command
fixes #811 and WD-22691
=> ensure app is initialized for any cluster manager command

service/microceph.go
During pipeline execution (e.g. https://github.com/canonical/microcloud/actions/runs/16517071789/job/46710255729?pr=893) we sometimes see that the request to add disks to MicroCeph exceeds the request context's deadline.
By default this deadline is set to 30s by the underlying Microcluster client. However when adding a large amount of disks we should give MicroCeph time to perform the necessary actions.
This should address one of the errors in https://github.com/canonical/microcloud/issues/653:
`⨯ Error: Failed to request disk addition: Post "http://control.socket/1.0/services/microceph/1.0/disks?target=micro01": context deadline exceeded`
=> Service: Increase the context deadline for adding MicroCeph disks

cmd/tui/autocomplete.go, cmd/tui/handler.go
=> Autocomplete fixes

doc/reference/releases-snaps.md
(cherry picked from commit 18a6508bda438e2a2c9f854e5d476cf2ff642f55)
=> Docs: Update link to MicroOVN release process (v2-edge)

demos/terraform/main.tf, demos/terraform/outputs.tf, demos/terraform/terraform.tfvars.example, demos/terraform/variables.tf
Fixes https://github.com/canonical/microcloud/pull/982#issuecomment-3285120879
=> Demos: use disk-by-id paths for storage devices in the Terraform demo
